### ISSUE TITLE
Trap device errors

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc-PG3/udi-poly-kasa#2]
Might already be fixed in this version, but need to check.
```
2021-12-29 09:28:43,729 Controller polyinterface      DEBUG    SmartStripPlugNode:cmd_set_on: Plug 1:cmd_set_on: is_on=False
2021-12-29 09:28:43,730 Controller polyinterface      INFO     polyinterface:reportDriver: Updating Driver 3c846a0c2bf701 - ST: 100, uom: 78
2021-12-29 09:28:43,741 Controller polyinterface      ERROR    polyinterface:_parseInput: _parseInput: failed 3c846a0c2bf701.runCmd(DON) Communication error on system:set_relay_state
Traceback (most recent call last):
  File "/var/polyglot/.local/lib/python3.8/site-packages/kasa/protocol.py", line 138, in _query
    return await asyncio.wait_for(
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/var/polyglot/.local/lib/python3.8/site-packages/kasa/protocol.py", line 99, in _execute_query
    packed_block_size = await self.reader.readexactly(self.BLOCK_SIZE)
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
RuntimeError: Task <Task pending name='Task-57' coro=<TPLinkSmartHomeProtocol._execute_query() running at /var/polyglot/.local/lib/python3.8/site-packages/kasa/protocol.py:99> cb=[_release_waiter(<Future pendi...8027d02e0>()]>)() at /usr/local/lib/python3.8/asyncio/tasks.py:429]> got Future <Future pending> attached to a different loop
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/polyglot/.local/lib/python3.8/site-packages/kasa/smartdevice.py", line 237, in _query_helper
    response = await self.protocol.query(request=request)
  File "/var/polyglot/.local/lib/python3.8/site-packages/kasa/protocol.py", line 71, in query
    return await self._query(request, retry_count, timeout)
  File "/var/polyglot/.local/lib/python3.8/site-packages/kasa/protocol.py", line 142, in _query
    await self.close()
  File "/var/polyglot/.local/lib/python3.8/site-packages/kasa/protocol.py", line 115, in close
    writer.close()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 353, in close
    return self._transport.close()
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 692, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/polyglot/.local/lib/python3.8/site-packages/polyinterface/polyinterface.py", line 842, in _parseInput
    self.nodes[input[key]['address']].runCmd(input[key])
  File "/var/polyglot/.local/lib/python3.8/site-packages/polyinterface/polyinterface.py", line 745, in runCmd
    fun(self, command)
  File "/var/polyglot/nodeservers/Kasa/nodes/SmartStripPlugNode.py", line 52, in cmd_set_on
    asyncio.run(self.dev.turn_on())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/var/polyglot/.local/lib/python3.8/site-packages/kasa/smartplug.py", line 53, in turn_on
    return await self._query_helper("system", "set_relay_state", {"state": 1})
  File "/var/polyglot/.local/lib/python3.8/site-packages/kasa/smartstrip.py", line 268, in _query_helper
    return await self.parent._query_helper(
  File "/var/polyglot/.local/lib/python3.8/site-packages/kasa/smartdevice.py", line 239, in _query_helper
    raise SmartDeviceException(f"Communication error on {target}:{cmd}") from ex
kasa.exceptions.SmartDeviceException: Communication error on system:set_relay_state
```

**Comment by jimboca** [comment]
Not an issue with latest version.
